theme: tailsaw

siteConfig:
  url: https://example.com
  author: Youness Lahdili
  email: author@gmail.com
  description: Ghadi ndir: Write an awesome description for your new site here. You can edit this line in saber-config.yml. It will appear in your document head meta (for Google search results) site description.

themeConfig:
  nav:
    - text: Home
      link: /
    - text: About
      link: /about.html
  social:
    twitter: ylahdili
    github: ylahdili
    rss: true

plugins:
  - saber-plugin-query-posts
  - saber-plugin-prismjs
  - saber-plugin-search
  - resolve: saber-plugin-query-posts
  - resolve: saber-plugin-feed
    options:
      atomFeed: true
